### ISSUE TITLE
Download artifacts 

### ISSUE THREAD

**Issue by Legion2** [OpenTOSCA/container-client#11]
Is it possible to download artifacts of a TOSCA Node Template?

**Comment by miwurster** [comment]
There isn't a specific method inside the client yet. However, the API to download CSAR content (e.g. artifacts) is already in place, see `http://localhost:1337/csars/../content/...`. As a workaround, you can call this API endpoint manually.
Alternatively, you could implement this for the `container-client` (be aware of PR #10) ;-)

**Comment by miwurster** [comment]
Since #10 has been merged, there is now the possibility to get a list of all files inside a CSAR. The respective download of such files needs to be implemented by yourself.
