### ISSUE TITLE
BoundaryDefinition Properties

### ISSUE THREAD

**Issue by Legion2** [OpenTOSCA/container-client#13]
Get BoundaryDefinition properties form `Application`.
Get BoundaryDefinition properties value from `ApplicationInstance`.

Example:
```
<BoundaryDefinitions xmlns="http://docs.oasis-open.org/tosca/ns/2011/12" xmlns:selfservice="http://www.eclipse.org/winery/model/selfservice" xmlns:winery="http://www.opentosca.org/winery/extensions/tosca/2013/02/12" xmlns:testwineryopentoscaorg="http://test.winery.opentosca.org">
    <Properties>
        <brokerAddress xmlns="" xmlns:ns5="http://docs.oasis-open.org/tosca/ns/2011/12">tcp://12.54.24.187</brokerAddress>
        <PropertyMappings>
            <PropertyMapping serviceTemplatePropertyRef="port" targetObjectRef="DockerContainer" targetPropertyRef="/*[local-name()='properties']/*[local-name()='Port']"/>
        </PropertyMappings>
    </Properties>
</BoundaryDefinitions>
```

**Comment by ghareeb-falazi** [comment]
According to the TOSCA 1.0 standard, the `Properties` section of the `BoundaryDefinitions` contains an XML segment that specifies global properties of the service template, but the schema of this segment is not defined. Therefore, the backend API, at the moment, returns it as a simple string (it does not assume it is a list of key-value pairs). For this reason getting the `BoundaryDefinition` properties from `Application` would contain a string representing this XML segment, and a list of `PropertyMapping`'s.

**Comment by Legion2** [comment]
Yeah I see that for the `Application`.
For the `ApplicationInstance` the `PropertyMapping`'s can be resolved to key-value pairs.
So for example in the given BoundaryDefinitions an `ApplicationInstance.get...("port")` should return the Port value of this instance.

**Comment by Legion2** [comment]
`ApplicationInstance.getProperty(string)` is not working as expected.
```xml
<ServiceTemplate name="MQTT-Broker-Service_w1" targetNamespace="http://legion2.github.io/tosca/servicetemplates" id="MQTT-Broker-Service_w1">
    <BoundaryDefinitions xmlns="http://docs.oasis-open.org/tosca/ns/2011/12">
        <Properties>
            <brokerAddress xmlns="" 
                xmlns:ns5="http://docs.oasis-open.org/tosca/ns/2011/12">tcp://12.54.24.187</brokerAddress>
            <PropertyMappings>
                <PropertyMapping serviceTemplatePropertyRef="port" targetObjectRef="DockerContainer" targetPropertyRef="/*[local-name()='properties']/*[local-name()='Port']"/>
            </PropertyMappings>
        </Properties>
    </BoundaryDefinitions>
    <TopologyTemplate>
        <NodeTemplate xmlns:otntyIgeneral="http://opentosca.org/nodetypes" name="DockerEngine" minInstances="1" maxInstances="1" type="otntyIgeneral:DockerEngine" id="DockerEngine">
            <Properties>
                <Properties xmlns="http://www.example.org">
                    <DockerEngineURL>tcp://dind:2375</DockerEngineURL>
                    <State>Running</State>
                </Properties>
            </Properties>
        </NodeTemplate>
        <NodeTemplate xmlns:otntyIgeneral="http://opentosca.org/nodetypes" name="DockerContainer" minInstances="1" maxInstances="1" type="otntyIgeneral:DockerContainer" id="DockerContainer">
            <Properties>
                <Properties xmlns="http://www.example.org">
                    <Port>9993</Port>
                    <ContainerPort>1883</ContainerPort>
                    <ImageID>eclipse-mosquitto:latest</ImageID>
                </Properties>
            </Properties>
        </NodeTemplate>
        <RelationshipTemplate xmlns:ToscaBaseTypes="http://docs.oasis-open.org/tosca/ns/2011/12/ToscaBaseTypes" name="con_1" type="ToscaBaseTypes:HostedOn" id="con_1">
            <SourceElement ref="DockerContainer"/>
            <TargetElement ref="DockerEngine"/>
        </RelationshipTemplate>
    </TopologyTemplate>
</ServiceTemplate>
```
**Expected**
When used with the above given ServiceTemplate, I expect the following to work.
```java
ContainerClient containerClient = ...;
Application application = ...;
ApplicationInstance applicationInstance = containerClient.getApplicationInstances(application).get(0);

String port = applicationInstance.getProperty("port");
assertThat(port, is("9993"));

String brokerAddress = applicationInstance.getProperty("brokerAddress");
assertThat(brokerAddress , is(someXMLFragment()));
```

**Actual**
`port` is `null` and `brokerAddress` is `"tcp://12.54.24.187"`

Note: `GET http://12.54.24.187/csars/MQTT-Broker-Service_w1.csar/servicetemplates/%257Bhttp:%252F%252Flegion2.github.io%252Ftosca%252Fservicetemplates%257DMQTT-Broker-Service_w1/instances/7/properties Headers: {'Accept': 'application/json'}` returns `{"brokerAddress":"tcp://12.54.24.187"}`

**Comment by ghareeb-falazi** [comment]
@Legion2 Apparently the XPath used to access Port is wrong: Try the following
`targetPropertyRef="//*[local-name()='Properties']/*[local-name()='Port']"` with // at the beginning to be able to access any nested level inside the node template, and with **P**roperties since XML is case-sensitive.

**Comment by Legion2** [comment]
The XPath was generated by winery.

**Comment by ghareeb-falazi** [comment]
Yes, this seems to be another problem. But could you try the XPath I provided so we know if Winery's problem is the only one?

**Comment by Legion2** [comment]
It don't work with your XPath, same result as with the old XPath.

**Comment by ghareeb-falazi** [comment]
So, it seems that there are multiple problems:
 *  A problem in the container that prevented evaluating property mappings (solved by https://github.com/OpenTOSCA/container/pull/98)
 * The xml-segment of boundary definitions should contain all properties, even the ones that will be evaluated by property mappings (according to TOSCA standard)
 * The `serviceTemplatePropertyRef` should be an xpath against the xml segment (according to TOSCA standard).
 * Winery generates faulty property mappings

An example of valid properties:
 


```xml
<BoundaryDefinitions xmlns="http://docs.oasis-open.org/tosca/ns/2011/12">
        <Properties>
            <Properties>
                <brokerAddress xmlns="" 
                xmlns:ns5="http://docs.oasis-open.org/tosca/ns/2011/12">tcp://12.54.24.187</brokerAddress>
                <port />
            <Properties>
            <PropertyMappings>
                <PropertyMapping serviceTemplatePropertyRef="//*[local-name()='port']" targetObjectRef="DockerContainer" targetPropertyRef="//*[local-name()='Properties']/*[local-name()='Port']"/>
            </PropertyMappings>
        </Properties>
</BoundaryDefinitions>
```

**Comment by Legion2** [comment]
Now a GET request to `...instances/7/properties` with Accept header `application/xml` returns  
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Properties xmlns="http://docs.oasis-open.org/tosca/ns/2011/12" xmlns:ns2="http://www.opentosca.org/winery/extensions/tosca/2013/02/12" xmlns:selfservice="http://www.eclipse.org/winery/model/selfservice" xmlns:testwineryopentoscaorg="http://test.winery.opentosca.org" xmlns:winery="http://www.opentosca.org/winery/extensions/tosca/2013/02/12"><port>9993</port><brokerAddress>tcp://12.54.24.187</brokerAddress>
                </Properties>
```
Thats good, but with Accept header `application/json` it returns 
```json
{"port":null,"brokerAddress":"tcp://12.54.24.187"}
```

**Comment by ghareeb-falazi** [comment]
The container now allows evaluating property mappings from the JSON endpoint as well as the XML endpoint.
Winery needs to be fixed to have a more clear handling of service template properties and property mappings (see https://github.com/OpenTOSCA/winery/issues/134)
